inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/dummy/db/**/*.rb'
    - 'vendor/**/*'
  TargetRubyVersion: 2.4

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'logux_rails.gemspec'
    - 'lib/logux/test/helpers.rb'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/logux_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/logux_controller.rb'
