inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/dummy/db/**/*.rb'
    - 'vendor/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'logux_rails.gemspec'

Metrics/AbcSize:
  Exclude:
    - 'app/controllers/logux_controller.rb'

Metrics/MethodLength:
  Exclude:
    - 'app/controllers/logux_controller.rb'
